/*
 * data.c - system probes for otop, backed by libonyxc syscalls.
 *
 * All numbers come from the kernel, not from synthetic values: the
 * /proc pseudo files (meminfo, load, cpuinfo, uptime) are generated by
 * OnyxKernel fs/procfs, the header fields via uname, and the own-heap
 * estimate via sbrk(0).
 */
#include "otop.h"

#define PROC_BUF 1024

/* Read a whole (small) procfs file into buf; returns bytes read. */
static int read_file(const char *path, char *buf, int cap) {
    int fd;
    long n;

    buf[0] = 0;
    fd = open(path, O_RDONLY, 0);
    if (fd < 0) return 0;
    n = read(fd, buf, cap - 1);
    close(fd);
    if (n < 0) n = 0;
    buf[n] = 0;
    return (int)n;
}

/* Own heap footprint: sbrk(0) growth relative to the first probe. */
long heap_self_kb(void) {
    static long base = 0;
    long now = (long)_onyx_sbrk(0);

    if (base == 0) base = now;
    return (now - base) / 1024;
}

/* Refresh a full system snapshot. Every source is optional: when a
 * /proc file is missing the corresponding fields simply stay 0 and the
 * panels render "(n/a)". */
void probe_collect(struct otop_info *oi) {
    char buf[PROC_BUF];

    memset(oi, 0, sizeof(*oi));

    if (read_file("/proc/meminfo", buf, sizeof(buf))) {
        parse_num(buf, "MemTotal", &oi->mem_total_kb);
        parse_num(buf, "MemFree", &oi->mem_free_kb);
        parse_num(buf, "MemUsed", &oi->mem_used_kb);
        parse_num(buf, "HeapTotal", &oi->heap_total_kb);
        parse_num(buf, "HeapUsed", &oi->heap_used_kb);
        parse_num(buf, "HeapFree", &oi->heap_free_kb);
    }

    if (read_file("/proc/load", buf, sizeof(buf))) {
        parse_num(buf, "processes", &oi->procs);
        parse_num(buf, "procs_running", &oi->running);
        parse_num(buf, "procs_blocked", &oi->blocked);
    }

    if (read_file("/proc/cpuinfo", buf, sizeof(buf))) {
        parse_num(buf, "harts", &oi->harts);
    }

    if (read_file("/proc/uptime", buf, sizeof(buf))) {
        oi->uptime_s = parse_uptime_s(buf);
    }

    _onyx_uname(&oi->un);
    oi->heap_self_kb = heap_self_kb();
}
